### ISSUE TITLE
Pencil pressure controls the brush size

### ISSUE THREAD

**Issue by fengeon** [fengeon/Resprite-doc#40]
When the apple pencil pressure is high, the brush size becomes larger.

General drawing software has this function, and the apple pencil also has a good pressure sensor.

 But the question is, is this feature useful in pixel art? What do you think?

**Comment by sancarr** [comment]
I think it would be quite useful for "painting-like" imagery & variation. I came across this awesome brush set for Procreate: https://ittaimanero.gumroad.com/l/ThePixelArtExperience

It is really awesome. If you check this image "Thin to Thick" the pressure sensitivity can be used for hair and other flowy elements.  (https://public-files.gumroad.com/cr1sjng7vgqjkn769lmvn8y9uz99)

Or check out these pressure sensitive dithering brushes: https://public-files.gumroad.com/3iuxfexojpk5o6hftswm8lse1mij
These are perfect for creating skidmarks, splatters etc etc 

Or imagine using a leaf/grass brush with pressure sensitivity to create layers and variations

I think adding pressure sensitivity with custom brush functionality is the way to go! 💯

Thank you for this amazing app btw, I haven't gotten it yet, waiting on my iPad and pencil to arrive. 
Your app I think is the best hands down 🙏🏽

**Comment by Dijakeen** [comment]
I think this function is necessary, I myself am just learning to draw pixel art and mainly draw in aseprite just with this function I was inspired by the artist who draws from a spot inventing his characters just with this function it is a pity that at the moment I can not completely move to this application because with a resolution closer to 64 by 64 this function I need.
I think many who like his style and try to draw like him also need this function and when they see that in this application it is not there they go to look for the next.

**Comment by fengeon** [comment]
works in r34
